BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "SensorData" (
	"dataEntryID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"sensorID"	INTEGER NOT NULL,
	"time"	INTEGER NOT NULL,
	"temperature"	REAL NOT NULL,
	"humidity"	REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS "Sensors" (
	"sensorID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"sensorName"	TEXT NOT NULL,
	"sensorLat"	REAL,
	"sensorLon"	REAL NOT NULL,
	"userID"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "APIKeys" (
	"apiKey"	TEXT NOT NULL UNIQUE,
	"userID"	INTEGER,
	PRIMARY KEY("apiKey")
);
CREATE TABLE IF NOT EXISTS "Users" (
	"userID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"userName"	TEXT NOT NULL,
	"userPassword"	TEXT NOT NULL,
	"userCookie"	TEXT,
	"cookieExpiry"	INTEGER
);
COMMIT;
